name: voice_recorder_app
description: A simple, intuitive and beautiful voice recorder app.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_sound: ^9.1.2
  assets_audio_player: ^3.0.4+1
  google_fonts: ^2.2.0
  sliding_sheet: ^0.5.2
  permission_handler: ^8.3.0
  stop_watch_timer: ^1.3.1
  path_provider: ^2.0.8
  intl: ^0.17.0
  flutter_dotenv: ^5.0.2
  logger: ^1.1.0
  share_plus: ^3.0.4
  wakelock: ^0.6.1+1
  auto_size_text: ^3.0.0
  flutter_vibrate: ^1.3.0

dev_dependencies:
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audios/